services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    env_file: 
      - .env

    volumes:
      - ./php-ini-overrides.ini:/usr/local/lsws/lsphp83/etc/php/8.3/mods-available/zz-overrides.ini:cached
      - ..:/var/www/vhosts/localhost/html:cached
      - ../..:/workspaces:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
  
  redis:
    image: valkey/valkey:9.1.2
    command: >
      valkey-server
      --port 6379
      --unixsocket /var/run/valkey/valkey.sock
      --unixsocketperm 777
    ports:
      - "6379:6379"
    volumes:
      - valkey-socket:/var/run/valkey

  db:
    image: mariadb:12.0.2
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 8306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mariadb

  typesense:
    image: typesense/typesense:30.2
    restart: always
    ports:
      - 8108:8108
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    
volumes:
  mariadb-data:
  valkey-socket:
  typesense-data:
