name: Build and deploy intranet stage.

on:
  workflow_dispatch:
  push:
    branches: [stage-intranet, develop-intranet]
    paths-ignore:
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: helsingborg-stad/municipio-deploy/4.0@master
      with:
        deploy-host: ${{ secrets.DEPLOY_REMOTE_HOST_STAGE_INTRA }}
        deploy-port: ${{ secrets.DEPLOY_REMOTE_PORT_STAGE_INTRA }}
        deploy-host-path: ${{ secrets.DEPLOY_REMOTE_PATH_STAGE_INTRA }}
        deploy-host-backup-path: ${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_STAGE_INTRA }}
        deploy-host-user: ${{ secrets.DEPLOY_REMOTE_USER_STAGE_INTRA }}
        deploy-host-user-key: ${{ secrets.DEPLOY_KEY_STAGE_INTRA }}
        deploy-host-web-server-user: ${{ secrets.WEB_SERVER_USER_STAGE_INTRA }}
        deploy-host-pagecache-path: ${{ secrets.DEPLOY_LS_PAGECACHE_PATH_STAGE_INTRA }}
        php-version: ${{ secrets.PHP_VERSION }}
        kill-lsphp: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        acf-url: ${{ secrets.ACF_URL }}
